### ISSUE TITLE
Resource naming conflict with newer versions of puppetlabs-concat

### ISSUE THREAD

**Issue by rneal** [adamcrews/puppet-splunkforwarder#11]
seen with concat (2.1.0):

Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Concat_fragment[inputs.conf_header] is already declared in file ***/modules/concat/manifests/init.pp:143; cannot redeclare at ***/modules/concat/manifests/fragment.pp:49 at ***/modules/concat/manifests/fragment.pp:49:3  at ***/modules/splunkforwarder/manifests/inputs.pp:100 on node whatever

**Comment by adamcrews** [comment]
This is fixed and released at https://github.com/adamcrews/puppet-splunkforwarder/releases/tag/v0.2.3

**Comment by adamcrews** [comment]
it maintains compatibility with both older and newer concat modules.
